# Generated by Django 5.1 on 2026-05-06 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(default='Mi Escuela', max_length=100)),
                ('color_primario', models.CharField(default='#0f172a', help_text='Código HEX (ej. #0f172a)', max_length=7)),
                ('color_secundario', models.CharField(default='#3b82f6', help_text='Código HEX (ej. #3b82f6)', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='portal/logos/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portal/portadas/')),
                ('titulo_landing', models.CharField(default='Bienvenidos al Portal Escolar', max_length=200)),
                ('texto_bienvenida', models.TextField(default='Aquí encontrarás todas las comunicaciones.')),
            ],
            options={
                'verbose_name': 'Configuración del Portal',
                'verbose_name_plural': 'Configuraciones del Portal',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 1ro A, 2do B', max_length=50)),
                ('turno', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('vespertino', 'Vespertino')], default='manana', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Grados',
                'ordering': ['turno', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Matemáticas, Educación Física', max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Acto del 25 de Mayo', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_evento', models.DateField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grados', models.ManyToManyField(related_name='galerias', to='comunicacion.grado')),
            ],
            options={
                'verbose_name_plural': 'Galerías',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galerias/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='comunicacion.galeria')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
                ('activo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grados', models.ManyToManyField(related_name='comunicados', to='comunicacion.grado')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comunicacion.materia')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='comunicados_imagenes/')),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='comunicacion.comunicado')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('grados_asignados', models.ManyToManyField(blank=True, related_name='docentes', to='comunicacion.grado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Docente',
                'verbose_name_plural': 'Perfiles de Docentes',
            },
        ),
    ]
