# Generated by Django 5.1 on 2026-05-07 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicado',
            options={'ordering': ['-fijado', '-fecha_publicacion']},
        ),
        migrations.RemoveField(
            model_name='perfildocente',
            name='grados_asignados',
        ),
        migrations.AddField(
            model_name='comunicado',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Solo para tareas con plazo', null=True),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='fijado',
            field=models.BooleanField(default=False, help_text='Los comunicados fijados aparecen siempre arriba'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='modificado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='tipo',
            field=models.CharField(choices=[('aviso', '📢 Aviso'), ('tarea', '📚 Tarea'), ('evento', '📅 Evento'), ('material', '📎 Material'), ('urgente', '🚨 Urgente')], default='aviso', max_length=20),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='urgente',
            field=models.BooleanField(default=False, help_text='Marca el comunicado con un badge rojo destacado'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='vistas',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='configuracionportal',
            name='email_contacto',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracionportal',
            name='whatsapp_escuela',
            field=models.CharField(blank=True, default='', help_text='Número con código de país, sin espacios. Ej: 5493624123456', max_length=30),
        ),
        migrations.AddField(
            model_name='galeria',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galerias_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galeria',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='modificado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galerias_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfildocente',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='perfildocente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='docentes/'),
        ),
        migrations.AddField(
            model_name='perfildocente',
            name='rol',
            field=models.CharField(choices=[('docente', 'Docente'), ('preceptor', 'Preceptor'), ('directivo', 'Directivo')], default='docente', max_length=20),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío para comunicados generales del aula (solo preceptores/directivos)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comunicacion.materia'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Creación'), ('editar', 'Edición'), ('eliminar', 'Eliminación'), ('publicar', 'Publicación')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objeto_repr', models.CharField(blank=True, default='', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cambios', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PerfilPadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, default='', max_length=20)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email_verificado', models.BooleanField(default=False)),
                ('notif_email', models.BooleanField(default=True, help_text='Recibir notificaciones por email')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('hijos_grados', models.ManyToManyField(blank=True, related_name='padres_seguidores', to='comunicacion.grado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_padre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Padre/Tutor',
                'verbose_name_plural': 'Perfiles de Padres/Tutores',
            },
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='comunicacion.perfildocente')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='comunicacion.grado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='comunicacion.materia')),
            ],
            options={
                'verbose_name': 'Asignación de Docente',
                'verbose_name_plural': 'Asignaciones de Docentes',
                'ordering': ['docente', 'grado', 'materia'],
                'unique_together': {('docente', 'grado', 'materia')},
            },
        ),
    ]
