# Generated by Django 5.1 on 2026-05-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0002_alter_comunicado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='ocultar_al_vencer',
            field=models.BooleanField(default=False, help_text='Si está marcado, el comunicado se oculta automáticamente del muro público después de la fecha de vencimiento.'),
        ),
        migrations.AddField(
            model_name='materia',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Color hex (ej: #fb923c). Si está vacío, se genera automáticamente del nombre.', max_length=7),
        ),
    ]
