# Generated by Django 5.1 on 2026-05-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0004_perfilducente_nuevos_campos_horariodocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='es_institucional',
            field=models.BooleanField(default=False, help_text='Comunicado de la institución (director). Sin materia, dirigido a la escuela.'),
        ),
    ]
