# Generated by Django 5.1 on 2026-05-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0006_recalcular_orden_grados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['orden', 'nombre'], 'verbose_name_plural': 'Grados'},
        ),
        migrations.AddField(
            model_name='configuracionportal',
            name='mensaje_bienvenida',
            field=models.CharField(blank=True, default='', help_text='Texto principal del landing. Ej: "Bienvenidos al Portal".', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionportal',
            name='mensaje_secundario',
            field=models.CharField(blank=True, default='', help_text='Texto debajo del mensaje principal. Ej: "Encontrá rápido el aula de tu hijo/a".', max_length=300),
        ),
        migrations.AddField(
            model_name='configuracionportal',
            name='mostrar_portada_grande',
            field=models.BooleanField(default=False, help_text='Si está activo, muestra el banner grande con la portada en el landing. Si no, muestra solo un header sutil.'),
        ),
    ]
