# Generated by Django 5.1 on 2026-05-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0007_alter_grado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpadre',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto opcional del padre/tutor', null=True, upload_to='padres/'),
        ),
        migrations.AddField(
            model_name='perfilpadre',
            name='tipo_notificacion',
            field=models.CharField(choices=[('todos', 'Recibir todos los avisos por email'), ('urgentes', 'Solo avisos marcados como urgentes'), ('ninguno', 'No recibir emails (entro al portal cuando quiero)')], default='todos', help_text='Qué emails quiere recibir el padre/tutor', max_length=20),
        ),
        migrations.CreateModel(
            name='HijoPadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre y apellido del hijo/a', max_length=100)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('grado', models.ForeignKey(help_text='Grado/aula que cursa este hijo/a', on_delete=django.db.models.deletion.PROTECT, related_name='alumnos_seguidos', to='comunicacion.grado')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='comunicacion.perfilpadre')),
            ],
            options={
                'verbose_name': 'Hijo/a de padre',
                'verbose_name_plural': 'Hijos/as de padres',
                'ordering': ['nombre'],
            },
        ),
    ]
