# Generated by Django 5.1 on 2026-05-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0009_migrar_hijos_padres'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildocente',
            name='puede_administrar_galerias_globales',
            field=models.BooleanField(default=False, help_text='Permite subir fotos a galerías no atadas a un aula específica.'),
        ),
        migrations.AddField(
            model_name='perfildocente',
            name='puede_administrar_materias_grados',
            field=models.BooleanField(default=False, help_text='Permite crear, editar y eliminar materias y grados.'),
        ),
        migrations.AddField(
            model_name='perfildocente',
            name='puede_editar_configuracion_portal',
            field=models.BooleanField(default=False, help_text='Permite editar logo, portada y mensajes generales del portal.'),
        ),
        migrations.AddField(
            model_name='perfildocente',
            name='puede_publicar_institucional',
            field=models.BooleanField(default=False, help_text='Permite publicar avisos institucionales dirigidos a toda la escuela.'),
        ),
        migrations.AddField(
            model_name='perfildocente',
            name='puede_ver_auditoria',
            field=models.BooleanField(default=False, help_text='Permite acceder al log de auditoría del sistema.'),
        ),
    ]
