# Generated by Django 5.1 on 2026-05-20 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0010_perfildocente_puede_administrar_galerias_globales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='archivado',
            field=models.BooleanField(default=False, help_text='Si está archivado, no se muestra en ningún lado pero no se borra de la base.'),
        ),
        migrations.CreateModel(
            name='ConsultaComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida')], default='pendiente', max_length=20)),
                ('archivada', models.BooleanField(default=False, help_text='Se archiva junto con el comunicado. El padre ya no puede escribir.')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='comunicacion.comunicado')),
                ('padre', models.ForeignKey(help_text='El padre/tutor que abrió la consulta.', on_delete=django.db.models.deletion.CASCADE, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta de comunicado',
                'verbose_name_plural': 'Consultas de comunicados',
                'ordering': ['-actualizada'],
                'unique_together': {('comunicado', 'padre')},
            },
        ),
        migrations.CreateModel(
            name='MensajeConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_del_docente', models.BooleanField(default=False, help_text='True si lo escribió el docente, False si lo escribió el padre.')),
                ('texto', models.TextField()),
                ('eliminado', models.BooleanField(default=False, help_text='Si el docente lo eliminó por moderación. Se muestra como "mensaje eliminado".')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_consulta', to=settings.AUTH_USER_MODEL)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='comunicacion.consultacomunicado')),
            ],
            options={
                'verbose_name': 'Mensaje de consulta',
                'verbose_name_plural': 'Mensajes de consulta',
                'ordering': ['creado'],
            },
        ),
    ]
