# Generated by Django 5.1 on 2026-05-20 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0011_comunicado_archivado_consultacomunicado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildocente',
            name='notif_mensajeria_email',
            field=models.BooleanField(default=False, help_text='Si está activo, recibe un email cuando le llega un mensaje interno.'),
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('directa', 'Directa (1 a 1)'), ('grupo', 'Grupo')], default='directa', max_length=10)),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre del grupo. Vacío para conversaciones directas.', max_length=120)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('creador', models.ForeignKey(help_text='Quién creó la conversación. En grupos, es el administrador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación interna',
                'verbose_name_plural': 'Conversaciones internas',
                'ordering': ['-actualizada'],
            },
        ),
        migrations.CreateModel(
            name='MensajeInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('eliminado', models.BooleanField(default=False, help_text='Si el autor lo eliminó. Se muestra como "mensaje eliminado".')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_internos', to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='comunicacion.conversacion')),
            ],
            options={
                'verbose_name': 'Mensaje interno',
                'verbose_name_plural': 'Mensajes internos',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='MiembroConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_lectura', models.DateTimeField(blank=True, help_text='Última vez que el usuario abrió esta conversación. Para contar no leídos.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='False si el usuario se salió del grupo. Conserva el historial.')),
                ('se_unio', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='comunicacion.conversacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de conversación',
                'verbose_name_plural': 'Miembros de conversación',
                'unique_together': {('conversacion', 'usuario')},
            },
        ),
    ]
