# Generated by Django 5.1 on 2026-05-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0012_perfildocente_notif_mensajeria_email_conversacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultacomunicado',
            name='docente_leyo',
            field=models.DateTimeField(blank=True, help_text='Última vez que el docente abrió este hilo.', null=True),
        ),
        migrations.AddField(
            model_name='consultacomunicado',
            name='padre_leyo',
            field=models.DateTimeField(blank=True, help_text='Última vez que el padre abrió este hilo. Para saber si leyó las respuestas.', null=True),
        ),
    ]
