# Generated by Django 5.1 on 2026-05-23 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0013_consultacomunicado_docente_leyo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaMuroPadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_visita', models.DateTimeField(auto_now=True, help_text='Se actualiza cada vez que el padre abre el muro de este grado.')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas_padres', to='comunicacion.grado')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas_muro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita al muro',
                'verbose_name_plural': 'Visitas a los muros',
                'unique_together': {('padre', 'grado')},
            },
        ),
    ]
